"""update

Revision ID: b044ab5fcf05
Revises:
Create Date: 2024-08-05 18:15:05.337587

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b044ab5fcf05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'chats',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('user_name', sa.String(), nullable=False),
        sa.Column('type', sa.Integer(), nullable=False),
        sa.Column('usage_times', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('user_id'),
    )
    op.create_table(
        'stats',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('incoming', sa.Integer(), nullable=False),
        sa.Column('outgoing', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'topics',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('topic_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['chats.user_id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'mappings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('source', sa.BigInteger(), nullable=False),
        sa.Column('topic_id', sa.BigInteger(), nullable=True),
        sa.Column('destination', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['topic_id'],
            ['topics.topic_id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['chats.user_id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mappings')
    op.drop_table('topics')
    op.drop_table('stats')
    op.drop_table('chats')
    # ### end Alembic commands ###
