"""Initial migration

Revision ID: 2745ac26978e
Revises:
Create Date: 2024-08-05 18:00:07.700454

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2745ac26978e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bots',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(length=32), nullable=False),
        sa.Column('name', sa.String(length=65), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('token', sa.String(length=45), nullable=False),
        sa.Column('owner', sa.BigInteger(), nullable=False),
        sa.Column('group', sa.BigInteger(), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('start_message', sa.String(length=4096), nullable=True),
        sa.Column('received_message', sa.String(length=4096), nullable=True),
        sa.Column('sent_message', sa.String(length=4096), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('token'),
        sa.UniqueConstraint('user_id'),
        sa.UniqueConstraint('username'),
    )
    op.create_table(
        'users',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('user_name', sa.String(), nullable=False),
        sa.Column('language', sa.String(length=2), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('user_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('bots')
    # ### end Alembic commands ###
