---
services:
  db:
    <<: *defaults
    image: public.ecr.aws/docker/library/postgres:18-alpine
    ports:
      - '127.0.0.1:${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 6

  app:
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_USE_SQLITE=false

volumes:
  postgres-data:
    driver: local
