# Generated by Codex on 2025-01-06

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [('feedback_bot', '0001_initial')]

    operations: ClassVar[list[Operation]] = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'bot',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='broadcast_messages',
                        to='feedback_bot.bot',
                    ),
                ),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(
                fields=['bot', 'chat_id'],
                name='broadcast_bot_chat_idx',
            ),
        ),
    ]
