# Generated by Django 5.2.7 on 2025-10-23 19:11

from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[list[str]] = [
        ('feedback_bot', '0003_banneduser_reason'),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.AlterField(
            model_name='messagemapping',
            name='owner_message_id',
            field=models.BigIntegerField(),
        ),
    ]
