# Generated by Django 5.2.7 on 2025-10-24 17:02

from typing import ClassVar

from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[list[str]] = [
        ('feedback_bot', '0004_alter_messagemapping_owner_message_id'),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.RemoveField(
            model_name='bot',
            name='confirmations_on',
        ),
    ]
