# Generated by Codex on 2025-02-14

from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ('feedback_bot', '0005_remove_bot_confirmations_on'),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.AddField(
            model_name='bot',
            name='allow_document_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='allow_photo_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='allow_sticker_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='allow_video_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='allow_voice_messages',
            field=models.BooleanField(default=True),
        ),
    ]
