# Generated by Django 5.2.7 on 2025-10-24 18:42

from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ('feedback_bot', '0006_bot_media_flags'),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.AddField(
            model_name='bot',
            name='antiflood_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='antiflood_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='feedbackchat',
            name='last_feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackchat',
            name='last_warning_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackchat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackchat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
