# Generated by Django 5.2.7 on 2025-10-24 20:34

from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ('feedback_bot', '0007_bot_antiflood_enabled_feedbackchat_last_feedback_at'),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.AddField(
            model_name='bot',
            name='communication_mode',
            field=models.CharField(
                choices=[
                    ('standard', 'standard'),
                    ('private', 'private'),
                    ('anonymous', 'anonymous'),
                ],
                default='standard',
                max_length=16,
            ),
        ),
    ]
