# Generated by Django 6.0.1 on 2026-03-16 18:25

from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ('feedback_bot', '0008_bot_communication_mode'),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.AddField(
            model_name='bot',
            name='use_topics',
            field=models.BooleanField(default=False),
        ),
    ]
